import { motion } from 'motion/react';
import { Link } from 'react-router-dom';
import { ShieldCheck } from 'lucide-react';
import './styles/PrivacyPolicy.css';

const effectiveDate = 'June 21, 2026';

function PrivacyPolicy() {
  return (
    <div className="privacy-page">
      <motion.section
        className="privacy-hero"
        initial={{ opacity: 0, y: 24 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.45 }}
      >
        <div className="privacy-hero-icon">
          <ShieldCheck size={34} aria-hidden="true" />
        </div>
        <p className="privacy-eyebrow">AWS Student Hub</p>
        <h1>Privacy Policy</h1>
        <p className="privacy-intro">
          This policy explains how the Wayne State University AWS Cloud Computing Club collects,
          uses, shares, and protects information through this website, member accounts, event tools,
          AWS challenges, and related club features.
        </p>
        <p className="privacy-date">Effective date: {effectiveDate}</p>
      </motion.section>

      <motion.div
        className="privacy-content"
        initial={{ opacity: 0, y: 18 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.45, delay: 0.12 }}
      >
        <section className="privacy-card privacy-callout">
          <h2>Account Deletion Requests</h2>
          <p>
            To delete your AWS Student Hub account, email{' '}
            <a href="mailto:awssbg@wayne.edu">awssbg@wayne.edu</a>. Please use the email address
            connected to your account when possible and include your username or full name so we can
            verify the request.
          </p>
          <p>
            Deletion may remove or anonymize account profile data, authentication records, challenge
            records, and related club records where practical. We may retain limited information
            when needed for security, abuse prevention, backups, event administration, dispute
            resolution, WSU reporting obligations, or other legitimate operational requirements.
          </p>
        </section>

        <section className="privacy-card">
          <h2>Information We Collect</h2>
          <p>
            We collect information you provide directly, information generated by your use of the
            site, and limited information from integrations you choose to use.
          </p>
          <ul>
            <li>
              Account information, including name, username, email address, password, account role,
              account status, creation date, last login, policy acknowledgement timestamps and
              versions, and password reset codes.
            </li>
            <li>
              Profile information, including profile photo, bio, major, grade, programming
              languages, email notification preference, and profile setup status.
            </li>
            <li>
              Authentication and session data, including access tokens, refresh tokens, browser
              device identifiers, remember-me preference, cached account data, and theme preference.
            </li>
            <li>
              Newsletter and event communication data, including subscribed email addresses and
              queued event notification records.
            </li>
            <li>Uploaded content, including profile pictures uploaded to the site.</li>
            <li>
              AWS challenge data, including challenge start/completion status, submissions,
              validation results, attempt counts, timestamps, reward status, and AWS challenge
              credentials assigned to your account.
            </li>
            <li>
              Prizeversity reward-linking data when you choose to link an account, including matched
              identifiers, classroom ID, Prizeversity user ID, linked email, short ID, verification
              code records, reward emissions, and reward delivery responses.
            </li>
            <li>
              Moderation and administration data, including role changes, bans, suspension status,
              ban reasons, and admin records needed to operate the club platform safely.
            </li>
            <li>
              Technical and security data, such as request metadata, error logs, browser storage
              data, and service health information used to secure and maintain the site.
            </li>
          </ul>
        </section>

        <section className="privacy-card">
          <h2>How We Use Information</h2>
          <ul>
            <li>To create, authenticate, secure, and manage member accounts.</li>
            <li>
              To provide member profiles, account settings, events, resources, and club updates.
            </li>
            <li>
              To run AWS challenges, provision challenge credentials, validate submissions, track
              progress, prevent abuse, and deliver eligible rewards.
            </li>
            <li>
              To link optional Prizeversity accounts, verify ownership, sync challenge reward
              activity, and prevent duplicate reward grants.
            </li>
            <li>
              To send password reset emails, event emails, newsletter updates, account notices, and
              administrative messages.
            </li>
            <li>
              To moderate the platform, investigate misuse, enforce club rules, enforce WSU-related
              expectations, and protect users and club resources.
            </li>
            <li>
              To improve reliability, debug errors, maintain backups, analyze aggregate usage, and
              protect the site from unauthorized access.
            </li>
          </ul>
        </section>

        <section className="privacy-card">
          <h2>Public Profiles and Visibility</h2>
          <p>
            Some profile information can be visible to other visitors or members. Public profile and
            member discovery features may show your username, full name, profile picture, bio,
            major, grade, programming languages, role, member-since information, and recent activity
            summary. Do not add personal information to your bio or profile photo that you do not
            want others to see.
          </p>
        </section>

        <section className="privacy-card">
          <h2>AWS Challenge Credentials</h2>
          <p>
            The site may provision AWS challenge credentials for your account. These credentials are
            intended only for club-authorized challenge work. Do not share, sell, publish, reuse, or
            misuse them. Misuse may lead to account restriction, credential revocation, reporting to
            club leadership, and referral to the appropriate Wayne State University offices or
            authorities.
          </p>
        </section>

        <section className="privacy-card">
          <h2>WSU Code of Conduct and Reporting</h2>
          <p>
            Because this club is affiliated with Wayne State University, all users must acknowledge
            and follow applicable WSU policies, including the Wayne State University Student Code of
            Conduct, when participating in club digital spaces, events, challenges, communications,
            and related activities.
          </p>
          <p>
            Harassment, discrimination, threats, intimidation, academic misconduct, unauthorized use
            of systems, credential misuse, impersonation, abuse of rewards, or mistreatment of other
            students, guests, officers, faculty, staff, or community members is not permitted.
            Concerns may be reported to club leadership at{' '}
            <a href="mailto:awssbg@wayne.edu">awssbg@wayne.edu</a> and, when appropriate, to the
            proper Wayne State University office or authority.
          </p>
          <div className="privacy-link-grid">
            <a
              href="https://doso.wayne.edu/care/student-conduct/code"
              target="_blank"
              rel="noreferrer"
            >
              WSU Student Code of Conduct
            </a>
            <a href="https://doso.wayne.edu/care/student-conduct" target="_blank" rel="noreferrer">
              WSU Student Conduct
            </a>
            <a
              href="https://doso.wayne.edu/care/student-conduct/non-academic-misconduct"
              target="_blank"
              rel="noreferrer"
            >
              Report Non-Academic Misconduct
            </a>
          </div>
        </section>

        <section className="privacy-card">
          <h2>When We Share Information</h2>
          <p>
            We do not sell your personal information. We may share information only as needed to run
            the site, provide requested features, protect the community, comply with obligations, or
            support club operations.
          </p>
          <ul>
            <li>
              Service providers may process information for authentication, hosting, database
              storage, file storage, email delivery, logging, and similar site operations.
            </li>
            <li>
              Auth providers such as Google/Auth0 may process identity information when you choose
              social login.
            </li>
            <li>
              AWS services may process uploaded files, hosted application data, challenge account
              data, and operational logs.
            </li>
            <li>
              Prizeversity may receive identifiers and challenge reward activity when you link your
              Prizeversity account or participate in reward-enabled challenges.
            </li>
            <li>
              Wayne State University offices or appropriate authorities may receive information when
              needed to report safety, conduct, harassment, discrimination, misuse, or policy
              concerns.
            </li>
            <li>
              We may disclose information if required by law, university process, security incident
              response, or a valid request from an authorized authority.
            </li>
          </ul>
        </section>

        <section className="privacy-card">
          <h2>Cookies, Browser Storage, and Tokens</h2>
          <p>
            The site uses browser storage and authentication tokens to keep you signed in, remember
            your theme, cache basic account data, maintain a browser device ID, support token
            refresh, and enable social login. Choosing "Remember me" may keep session data in
            localStorage; otherwise, session data may be stored in sessionStorage. You can clear
            this information through your browser, but doing so may sign you out or reset
            preferences.
          </p>
        </section>

        <section className="privacy-card">
          <h2>Your Choices</h2>
          <ul>
            <li>You can update most profile information from the account settings page.</li>
            <li>You can turn event email notifications on or off in your account settings.</li>
            <li>
              You can unsubscribe from newsletter communications by contacting club leadership.
            </li>
            <li>You can unlink your Prizeversity account from account settings when available.</li>
            <li>You can sign out from the current device or request broader account support.</li>
            <li>
              You can request account deletion by emailing{' '}
              <a href="mailto:awssbg@wayne.edu">awssbg@wayne.edu</a>.
            </li>
          </ul>
        </section>

        <section className="privacy-card">
          <h2>Data Retention</h2>
          <p>
            We keep personal information for as long as reasonably needed to provide the site,
            operate the club platform, maintain security, administer events and challenges, resolve
            disputes, enforce rules, support WSU-related reporting, and meet technical or legal
            obligations. Backup copies, logs, moderation records, security records, reward records,
            and records connected to reports or investigations may remain for longer when necessary.
          </p>
        </section>

        <section className="privacy-card">
          <h2>Security</h2>
          <p>
            We use practical safeguards such as hashed passwords, token-based authentication,
            role-based administration, upload limits, access controls, and provider security
            features. No website can guarantee absolute security. You are responsible for keeping
            your password, account access, and AWS challenge credentials private.
          </p>
        </section>

        <section className="privacy-card">
          <h2>Children</h2>
          <p>
            The site is intended for Wayne State University students, club participants, and invited
            community members. It is not directed to children under 13. If you believe a child under
            13 provided personal information through the site, contact us so we can review and
            remove it where appropriate.
          </p>
        </section>

        <section className="privacy-card">
          <h2>Changes to This Policy</h2>
          <p>
            We may update this policy as club operations, site features, integrations, or university
            requirements change. The effective date above will be updated when material changes are
            made.
          </p>
        </section>

        <section className="privacy-card">
          <h2>Contact</h2>
          <p>
            For privacy questions, account deletion, or conduct-related concerns connected to this
            site, contact <a href="mailto:awssbg@wayne.edu">awssbg@wayne.edu</a>. For general site
            navigation, return to the <Link to="/">AWS Student Hub home page</Link>.
          </p>
        </section>
      </motion.div>
    </div>
  );
}

export default PrivacyPolicy;
