name: Deploy Lambda Backend

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
  workflow_dispatch: # manual trigger

env:
  AWS_REGION: us-east-1

jobs:
  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Setup AWS SAM
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to Development
      working-directory: backend
      run: |
        chmod +x ./deploy.sh
        ./deploy.sh dev "${{ secrets.MONGODB_URI }}" "${{ secrets.JWT_SECRET }}" "${{ secrets.CORS_ORIGIN }}" "${{ secrets.S3_BUCKET_NAME }}" "${{ secrets.S3_ACCESS_KEY_ID }}" "${{ secrets.S3_SECRET_ACCESS_KEY }}" "${{ secrets.S3_REGION }}"

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-dev
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    environment: production 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Setup AWS SAM
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to Production
      working-directory: backend
      run: |
        chmod +x ./deploy.sh
        ./deploy.sh prod "${{ secrets.MONGODB_URI }}" "${{ secrets.JWT_SECRET }}" "${{ secrets.CORS_ORIGIN }}" "${{ secrets.S3_BUCKET_NAME }}" "${{ secrets.S3_ACCESS_KEY_ID }}" "${{ secrets.S3_SECRET_ACCESS_KEY }}" "${{ secrets.S3_REGION }}" 